export const POPULAR_POSTS_PAGE_LIMIT = 12;
export const POPULAR_POSTS_LOAD_MORE_ROOT_MARGIN = '240px 0px';
export const POPULAR_SNAPSHOT_EXPIRED_ERROR_CODE = 'POPULAR_SNAPSHOT_EXPIRED';
export const FEED_INITIAL_SKELETON_COUNT = 6;
export const FEED_LOAD_MORE_SKELETON_COUNT = 3;
