export const FOLLOW_LIST_PAGE_LIMIT = 20;
export const PROFILE_POSTS_PAGE_LIMIT = 20;
export const PROFILE_DRAFTS_POLL_INITIAL_INTERVAL_MS = 5000;
export const PROFILE_DRAFTS_POLL_MAX_INTERVAL_MS = 30000;
export const MAX_PROFILE_AVATAR_BYTES = 5 * 1024 * 1024;
export const PROFILE_LINK_MAX_LENGTH = 2048;
