export const NOTIFICATIONS_PAGE_LIMIT = 20;
export const NOTIFICATIONS_PREVIEW_LIMIT = 8;
export const NOTIFICATIONS_BADGE_MAX = 50;
export const NOTIFICATIONS_LOAD_MORE_ROOT_MARGIN = '280px 0px';
export const NOTIFICATIONS_POLL_VISIBLE_INTERVAL_MS = 30_000;
export const NOTIFICATIONS_POLL_HIDDEN_INTERVAL_MS = 120_000;
export const NOTIFICATIONS_POLL_ERROR_MAX_INTERVAL_MS = 300_000;
